### ISSUE TITLE
Evaluate specview units code for our use

### ISSUE THREAD

**Issue by eholum** [ChandraCXC/iris#154]

**Comment by olaurino** [comment]
PR #168 has a lot of working useful for this task. As a matter of fact it might indeed be seen as showing that the specview code could indeed be included, modulo extensive refactoring, into Iris.

However, there are now two places in the code base that have to do with units, and they should be unified: one is package cfa.vo.iris.sed.quantities and one is package cfa.vo.units. Both are in iris-common.

**Comment by eholum** [comment]
We're definitely using it - and there's more work here that needs to be done as @olaurino mentions above. We have units code in two places and they need to be merged. Will track that in new tasks.

For now the units code from specview is already in iris. So calling this guy done.
