### ISSUE TITLE
Research how to attach pull requests to tasks

### ISSUE THREAD

**Issue by eholum** [ChandraCXC/iris#169]
And instruct others so that we don't clutter our task list with pull requests.

**Comment by olaurino** [comment]
If it's just a matter of clutter, we can filter out PRs by clicking on the filter icon in the top right corner of the Waffle GUI. However, here are the instructions for connecting PRs to tasks:
https://github.com/waffleio/waffle.io/wiki/FAQs#prs-closing-keywords

I tried with PR 168, and it seems to work (you may need to refresh the waffle board). I'll update the other PRs. Let's keep this task open, as we need to add proper instructions to our UDF.

**Comment by olaurino** [comment]
Some PRs remain visible despite my attempts, however when I filter them out in Waffle I don't see them anymore in their own boxes but they are attached to the tasks, so that's probably the best solution.

**Comment by olaurino** [comment]
Note that "resolve #xxx" will also cause the #xxx task/issue to be closed in GitHub and moved to Done in Waffle. This should be OK, but worth mentioning.
