### ISSUE TITLE
Clean up logging/stdout for unit tests during build

### ISSUE THREAD

**Issue by eholum** [ChandraCXC/iris#176]
There's a lot of junk coming out builds on the command line that we don't need. Set the logger to only log severe/maybe redirect stdout/stderr somewhere?

We should only see details for specific tests if that test fails.

**Comment by olaurino** [comment]
I wrote the following patch the other day:
https://github.com/ChandraCXC/iris/compare/silence-test-log

Of course it does not prevent tests from writing to System.out, but that is redirected to file as well (see the second commit). The logs and outputs are stored in the individual submodule's `target/surefire-reports/` folder.

It seems to work:
https://travis-ci.org/ChandraCXC/iris/jobs/89059956

My prototype only deals with Surefire. The same configuration should be added to Failsafe. Maybe there is a way to apply some configurations to both... that would be nice.

**Comment by eholum** [comment]
https://github.com/ChandraCXC/iris/commit/ebc29f73ff3ed24134eff40fd9a36ec4b1059402
