### ISSUE TITLE
Document which Tests Setup SAMP and What they Do

### ISSUE THREAD

**Issue by eholum** [ChandraCXC/iris#190]
Just documentation - and perhaps whether or not each one should be a unit test or a integration test

**Comment by eholum** [comment]
iris-common
* cfa.vo.iris.common.SedMessageTest
  * Starts SAMP server, loads up SED, sends SAMP message, verifies SED
* cfa.vo.iris.test.SampUISpecAdapter
  * Doesn't necessarily use it, but is related so including it in this list.
* cfa.vo.interop.SAMPFactoryTest
  * Sets up SAMP and verifies createMessage, getting different class types

These tests all need Sherpa-SAMP up, and related to testing the SEDStacker in sed-builder
* cfa.vo.sed.science.stacker.AbstractSAMPIntegrationTest
  * Just a parent to the SED Stacker classes. Anything that sets up a SAMP controller should be in Iris common and this should just hold relevant stuff for the stacker related classes.
* cfa.vo.sed.science.stacker.SedStackerNormalizerIT
* cfa.vo.sed.science.stacker.SedStackerRedshifterIT
* cfa.vo.sed.science.stacker.SedStackerStackerIT
  *  The previous three are related to SEDStacker calls that rely on Sherpa/SAMP messages.
* cfa.vo.sed.science.interpolation.SherpaRedshifterTest => Should be renamed

**Comment by jbudynk** [comment]
`cfa.vo.interop.SAMPFactoryTest` doesn't (and doesn't need to) connect to a SAMP Hub. It just tests that the messages it sends to a SAMP hub are correct.
