### ISSUE TITLE
Fix Travis-CI for Noncached Systems

### ISSUE THREAD

**Issue by eholum** [ChandraCXC/iris#206]
If a user forks Iris, hooks Travis-CI to their fork, and pushes a commit, the Travis build will error with

```
The command "conda update --yes conda" failed and exited with 127 during .
```

See https://travis-ci.org/jbudynk/iris/jobs/94492422 for the full output.

The path to some of the cached systems, like Miniconda in this case, is invalid due updates to whatever is being installed. We need to make sure new users that setup Travis-CI can build their forks successfully.

**Comment by olaurino** [comment]
The only (slightly) tricky part is that this should be done so that it keeps working on cached environments.

Here is the change in Sherpa's repo:
sherpa/sherpa@d177b6
