### ISSUE TITLE
Find High Definition Spectrum Datasets

### ISSUE THREAD

**Issue by eholum** [ChandraCXC/iris#226]
That are in an Iris-usable format

**Comment by jbudynk** [comment]
Here are two files of spectra from HARPS-N, a fiber-fed echelle spectrograph. **Both files need to be reformatted to read into Iris.**

  * [HARPN.2012-08-10T21-10-19.676_s1d_A.fits](https://drive.google.com/open?id=0BwbX0VxOVx-iSE1PajVOSDh4R1U). This is a 1-D spectrum with over 300,000 data points.
  * [HARPN.2012-08-10T21-10-19.676_e2ds_A.fits](https://drive.google.com/a/cfa.harvard.edu/folderview?id=0BwbX0VxOVx-iZWRZZEdCV1VkTjQ&usp=sharing). This is a "2-D spectrum." Each row in the FITS image is a spectrum. The left and right ends of the spectra overlap in wavelength with the spectra above and below it. Each spectrum contains 4096 points. 

The 1-D spectrum is the merged version of the 2-D spectrum.

We can use the 2-D spectrum for testing large co-plot views for relatively "normal" size spectra.

The files were taken from the TNG archive: http://ia2.oats.inaf.it/archives/tng

**Comment by jbudynk** [comment]
I've created Iris-readable files for testing from these HARPS files. You can find them [here](https://drive.google.com/open?id=0BwbX0VxOVx-iZWRZZEdCV1VkTjQ). The files in `e2ds_spectra/`are derivied from HARPN.2012-08-10T21-10-19.676_e2ds_A.fits; these have 4096 points. The file [HARPN.2012-08-10T21-10-19.676_s1d_A_formatted.fits](https://drive.google.com/open?id=0BwbX0VxOVx-iQnpsdURUU0c1OGM) is the 300,000 1D spectrum.

These are not VO compliant files, but you can use the importer to convert them.

**Comment by jbudynk** [comment]
I've converted these to VO-compliant format:

   - 300,000 point spectrum: [test300k_VO.fits](https://drive.google.com/open?id=0BwbX0VxOVx-iYllmMmQwdzJBRVU)
   - 4000 point spectra: [e2ds_spectra/vo-format/](https://drive.google.com/open?id=0BwbX0VxOVx-iUFpBR3hnUUtjS2s)
