### ISSUE TITLE
Issue with plotting segments with the same Target name

### ISSUE THREAD

**Issue by jbudynk** [ChandraCXC/iris#258]
If two SED segments share the same Target name, only one of them is shown on the Plotter. I believe the top-most segment of the same Target name is shown. Both segments appear in the Metadata Browser.

Test data: [Iris/github-issue-attachments/258](https://drive.google.com/open?id=0BwbX0VxOVx-iT3hxYm1zbXNoY1E)

This is on the master branch at 646227a, but is also present in sprint-5 at 8fb56eb

**Comment by eholum** [comment]
Closed in https://github.com/ChandraCXC/iris/pull/257
