### ISSUE TITLE
Saving a Segment: All segments besides the selected one are removed from the SED Builder view

### ISSUE THREAD

**Issue by jbudynk** [ChandraCXC/iris#259]
To reproduce:

Load a 5 NED SEDs (for example: m81, m82, m83, m84, m85).
Select the 3rd one and click the "Save" button.

The other segments will disappear from the Segments table.

However, if you switch to a another SED and back to this one, you'll see all the original segments are in the table.

**Comment by jbudynk** [comment]
In SedBuilderMainView.java, in function saveSegments():

```
    @Action
    public void saveSegments() {
        try {
            ExtSed s = new ExtSed("");
            s.addSegment(selectedSegments);
            SaveSedDialog ssd = new SaveSedDialog(rootFrame, s, false);
            ssd.setVisible(true);
```

The issue occurs at `s.addSegment(selectedSegments);`. If I comment out the code related to opening the SaveSedDialog frame, I still see the issue. If I then comment out everything except creating the new ExtSed, I don't see the other unselected Segments disappearing. E.g.,

```
    @Action
    public void saveSegments() {
        try {
            ExtSed s = new ExtSed("");
//            s.addSegment(selectedSegments);    // Segments disappear if I uncomment this line
//            SaveSedDialog ssd = new SaveSedDialog(rootFrame, s, false);   // Segments remain in table if I uncomment this.
//            ssd.setVisible(true);
```

**Comment by olaurino** [comment]
I think this is fixed by making the new SED unmanaged.
