### ISSUE TITLE
specview dependency

### ISSUE THREAD

**Issue by SaOgaz** [ChandraCXC/iris#360]
Hi,

STScI will be pulling specview soon, and I wanted to double check with your group that it will not effect you.  It looks like the dependency on external specview was removed with a prior merge, but I wanted to make absolutely sure.

Thanks!

**Comment by jbudynk** [comment]
Hi @SaraOgaz,

Yes, we've removed specview as a dependency, so Iris should be fine. Thanks for the heads up!

**Comment by SaOgaz** [comment]
Thanks @jbudynk, closing issue.
