### ISSUE TITLE
Change default Iris log location and name, plus make it configurable by the user

### ISSUE THREAD

**Issue by olaurino** [ChandraCXC/iris#58]
Iris log files are created in the home directory and with a non-human-readable timestamp.

It would be desirable to have the log file default location moved to $HOME/.vao/iris/, and maybe have both the location and name configurable by the user (environment variables?)

Moreover, changing the timestamp to a human-readable format would be good as well.

**Comment by jbudynk** [comment]
I tested this on the conda build hosted on https://binstar.org/olaurino/iris/files. It works. 

Environment variables the user needs to set are IRIS_LOG_LOCATION and IRIS_LOG_NAME. The timestamp is appended to IRIS_LOG_NAME.
