### ISSUE TITLE
Adding new Segments to SEDs

### ISSUE THREAD

**Issue by jbudynk** [ChandraCXC/iris#59]
On my system, I noticed that I cannot add new Segments to SEDs. It looks like the bug we had with adding new Segments to redshifted SEDs (#30). 

The bug appears in commit 74e597f3ec5f4, which is a merge of  38ed85d   and   c165f04.

commit  c165f04  is fine. 
commit  38ed85d  however is broken. I noticed that running "mvn install" on the commit before 38ed85d, merge commit 4e5c9a1,  causes a BUILD FAILURE:

/Users/jbudynk/test/iris/sed-builder/src/main/java/cfa/vo/sed/science/integration/SherpaIntegrator.java:[91,32] error: cannot find symbol

I haven't had time to look into this bug, but it looks like this bug persisted through to the current state of the develop branch (commit 76381ac25b77bcd).

**Comment by olaurino** [comment]
Note: to reproduce this bug in a build from commit 74e597f

Start Iris with the --test flag. Add a SED with the test builder, then add a NED segment. Fit the SED, then try to close the fitting manager main window. A dialog will ask if you want to keep the model: say yes.

Now try to add a user segment to the SED: the new segment will not be displayed by the viewer.
