### ISSUE TITLE
“Statistics” drop-down menu disappears.

### ISSUE THREAD

**Issue by olaurino** [ChandraCXC/iris#77]
Open two SEDs. Start a fitting session on one. Do a fit. Switch to the second SED. Start a fitting session, and do a fit. On switching back to the first SED, the Statistics drop-down menu is missing. This is repeatable. WORKAROUND: exit the statistics window and click “Fit” from the main Fitting Tool to open a new statistics window.

**Comment by jbudynk** [comment]
For now, we'll add this workaround to the web docs.
