### ISSUE TITLE
User-defined fitting functions/templates/models in the added components list are not listed by their component ID’s

### ISSUE THREAD

**Issue by olaurino** [ChandraCXC/iris#78]
Python functions are listed as “usermodel,” template libraries are called “templates” and table models are “tablemodel.” This is also an issue for saving fitting sessions to text files. E.g., here’s example output of saving a model that’s a powerlaw + a user template library called “my-templates:”

 File: Sed0
Tue Feb 24 15:17:14 EST 2015  Iris 2
TARGNAME: Sed0

Model Expression:
    	c1+c2

Fit parameters:
    	Final fit statistic:  	1.8079001468311147e-05
    	Reduced statistic:    	nan
    	Probability [Q-value]:	nan
    	Degrees of freedom:   	29.0
    	Data points:          	33
    	Last function evaluation: 131

Component 1: template
	idx   = -0.14201593                                        
 	refer = 5000.0

Component 2: blackbody
   F   refer   	= 5000.0    	angstroms
        ampl    	= 6.134682E-4
   temperature = 3008.0027 	Kelvin

“template” should be “my-templates”

**Comment by jbudynk** [comment]
Add a note in "Caveats & Bugs," and possibly "Fitting and Modeling"
