### ISSUE TITLE
VAO name in the Iris logo

### ISSUE THREAD

**Issue by olaurino** [ChandraCXC/iris#84]

**Comment by jbudynk** [comment]
one issue - the old Iris logo with VAO in it is in the SED Viewer when a user tries to view an empty SED. I think this image is in the Specview package, as I can't find another Iris logo file in the iris package.
![uploads/8d26e99a-4496-408e-81e0-e2e7410e59e9/Screen Shot 2015-04-26 at 12.22.09 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F8d26e99a-4496-408e-81e0-e2e7410e59e9%2FScreen+Shot+2015-04-26+at+12.22.09+PM.png)

**Comment by jbudynk** [comment]
The image is embedded in Specview. Leaving it as-is. Too much work to go into Specview for now.
