### ISSUE TITLE
In the fit model "brokenpowerlaw" there is missing a parameter stating the frequency of the break

### ISSUE THREAD

**Issue by olaurino** [ChandraCXC/iris#88]
We should clarify in the docs that "refer" is the parameter for the frequency break. Should we add this to the tooltip? (I know Ivo's the one who needs to fix this issue...)

**Comment by jbudynk** [comment]
I'll add it to the Iris webdocs for the iris 2.1 release.

**Comment by jbudynk** [comment]
The web docs already say that "refer" is the break wavelength, in Angstroms. See cxc.cfa.harvard.edu/iris/v2.1/references/models.html#brokenpowerlaw.

I've added links to all the models in the docs (see cxc-dmz-prev.cfa.harvard.edu/iris/v2.1/threads/fit, /science, /analysis). Now the user can follow the link to the references/models.html#<model_name>. When the model is not referenced  by its model name in Iris (e.g., "log-parabola" vs "logparabola"), it is NOT linked to the models page.
