### ISSUE TITLE
SED STACKER - GUI: update layout

### ISSUE THREAD

**Issue by jbudynk** [ChandraCXC/iris#97]
I think that the layout of the sections of the SED stacker frame can be improved. As it is, it does not feel “natural” for the user. You could try to implement a “vertically aligned” layout. 

Users create a new stack in the leftmost section “Open Stacks”, and the “Management” commands can be found immediately below the “Open Stacks” window, in a more comfortable position. Then, users can add SEDs to the stack just created by populating the “Added SEDs” section which would be located right next of the “Open Stacks” window. The other functions in “Redshift and Normalize” and the “Stacking Options” should be located in the right­most position of the SED Stacker window.

**Comment by jbudynk** [comment]
I've got two visions for the GUI, both of which are in the sedstacker-enhancements branch. Which layout looks better?

This one follows Rafaelle's description exactly:
![sedstacker-1](https://cloud.githubusercontent.com/assets/6233750/16956505/b3f0c834-4da6-11e6-858a-61c1fa4d0572.png)

In this one, I moved the stacking options to their own tab:
![sedstacker-2](https://cloud.githubusercontent.com/assets/6233750/16956536/dba1bbb8-4da6-11e6-8e9e-c3c7f346847c.png)
![sedstacker-3](https://cloud.githubusercontent.com/assets/6233750/16956543/deb131b2-4da6-11e6-8d85-79cc76b006a1.png)

**Comment by olaurino** [comment]
I am ok with this changes going in if the amount of work is minimal: as Jamie mentioned, it's good to show Raffaele we got some of his feedback into account, but this is not a functional change. So, from me, go with whatever your preferred option is: if this takes more than a couple of hours to implement, let's take a step back and re-evaluate.
